[ids]

*

[main]

# 1. Map tapping left Super to Super+O, while holding it acts as normal Super (meta)
leftmeta = overload(meta, M-o)

rightalt = layer(nav)

# Maps capslock to escape when pressed and control when held.
capslock = esc

# Remaps the escape key to capslock
esc = capslock

[nav]

h = left
j = down
k = up
l = right
u = leftmouse
i = middlemouse
o = rightmouse

# --- New Layers Added Below ---

[meta]
# 2. Map Super + Scroll Up/Down to Super + Up/Down
scrollup = M-up
scrolldown = M-down

[alt]
# 3. Map Alt + Scroll Up/Down to Super + Left/Right
scrollup = M-left
scrolldown = M-right
